### ISSUE TITLE
Broken after Upgrade to 2.0.1 (java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/SyncedGuiDescription)

### ISSUE THREAD

**Issue by Richie1710** [4nner/IronChests#59]
Minecraft: 1.20.1
Fabric:  0.14.24

After Upgrading Ironchest to 2.0.1 Version I'm facinging following issue 

`java.lang.NoClassDefFoundError: io/github/cottonmc/cotton/gui/SyncedGuiDescription`

Crash log attached 

[crash-2023-11-05_08.47.04-client.txt](https://github.com/4nner/IronChests/files/13258940/crash-2023-11-05_08.47.04-client.txt)

**Comment by woodiertexas** [comment]
Same here: https://mclo.gs/vUwNdip

**Comment by 4nner** [comment]
@Richie1710 @woodiertexas Apologies for the issue. Version 2.0.1 has been released and tested for MC 1.20.2, while you are both on MC 1.20.1. While this does not make a big difference for the mod, its dependency LibGui apparently does not run on 1.20.1
You will have to revert back to 2.0.0. I have removed the 1.20.0 and 1.20.1 tags from both Curseforge and Modrith, to avoid confusion.
Thank you for the report :)
